### ISSUE TITLE
[BE-REFACTOR] 데이터 처리 방식 변경

### ISSUE THREAD

**Issue by dwax1324** [woowacourse-teams/2024-pokerogue-helper#203]
✨ Description
---

## 문제

현재까지 백엔드의 태스크를 봤을 때 가장 많이 막혔는 부분은

- 기초 공사(4인 페어 컨벤션)
- 인프라
- 서버 안정화, 최적화
- 데이터 추출, 업데이트

라고 생각합니다.

특히 필요한 데이터를 추출, 저장하는 과정에서 `PokeApi`를 사용하여 데이터베이스에 **저장**하고 **업데이트 자동화**까지하는 부분에서 많은 시간을 빼았겼습니다. 프로젝트 시작부터 현재까지 팀원 한 명이 이걸 도맡아서 했고, 다같이 그에 대한 코드리뷰까지 하면서 개인적으로 한 명 이상의 큰 리소스가 들었다고 생각합니다.

포케로그에서 `PokeApi`를 사용하고 있는 것이 맞지만 그 데이터를 어떻게 가공해서 게임에 적용시켰을지는 모릅니다. 어플리케이션의 정체성을 `pokerogue-helper`로 정한 이상 포케로그에 대한 의존성은 떨쳐낼 수 없습니다.  `PokeApi`를 사용한다면, `PokeApi`에서 정보를 가져와서 저장해도 포케로그의 실제 게임 플레이와 일치하는지 `검증`해야하는 과정이 추가됩니다. 결국에는 포케로그 깃허브 오픈소스를 까봐야한다는 소리가 됩니다.

이쯤에서 불필요한 일을 하고있지 않나라는 생각이 들었습니다. 사실 `데이터 추출과 업데이트`는 그렇게 리소스가 크게 드는 작업이 아닙니다. 다만, 이것을 `Java`라는 verbose한 언어로 비효율적으로 처리하고 데이터베이스에 굳이 저장하여 testDB, localDB, productionDB의 ERD가 싱크로나이즈 되어야 합니다. 이 과정에서 크고 작은 에러들이 많이 발생하고 시간을 많이 빼앗깃 수밖에 없습니다.

주말동안 포케로그 오픈소스 레포지토리를 분석해 본 결과, 모든 것이 하드코딩 되어있습니다. 하드코딩이라기 보다는, 하드코딩을 하는 코드를 작성해서 자동화하였습니다. 추출한 데이터를 데이터베이스에 저장하지는 않습니다. 애초에 데이터가 디비에 저장되어 있을 필요가 없습니다. 이미지, 사운드, 게임로직, 포켓몬 등등 모두 포함하여 2.7GB밖에 되지 않았고 저희가 필요한 정보만 빼낸다면 용량도 무척 적을 것입니다. 포케로그에도 서버 레포지토리가 있지만, 민감한 유저 정보만 저장하는 용도로만 쓰입니다. 반면에 포켓몬 정보는 언제든지 정보를 가져올 수 있습니다. 현재 데이터베이스 업데이트를 해도 모든 데이터를 지우고 똑같은 데이터를 집어넣는 과정인데, 한 번당 약 30분이 필요했었습니다. 이게 필요한 과정인지 잘 모르겠습니다.

데이터 저장을 **인메모리 저장 방식**(그냥 txt파일, h2도 괜찮을지도?)으로 바꾸는 것을 제안합니다. 개발 서버에 데이터를 저장한다면 ERD를 신경쓸 필요도 없어집니다. 작업 효율이 상당히 올라갈겁니다. 안드로이드에서 필요한 정보를 빠르게 전달할 수 있을 것입니다. 팀을 위해서라면 이 방식이 맞다고 생각합니다. 또한 필요한 정보가 추가될 때가 많은 프로젝트 특성상 동적쿼리를 사용해 API를 단순화 시키는 것이 어떨지 제안해봅니다.

현재 회의 시간에 얘기했던 포켓몬 상세에 대한 정보는 모두 추출했습니다
```java
"pokemonId",
"speciesId",
"name",
"type1",
"type2",
"ability1",
"ability2",
"abilityHidden",
"abilityPassive",
"generation",
"legendary",
"subLegendary",
"mythical",
"evolution",
"baseTotal",
"baseStats",
"height",
"weight",
"form",
"eggMoves",
"moves",
"biomes"
```

동적 쿼리를 사용해 위에서 제공 가능한 정보 중 아래와 같이 필요한 정보만 쿼리하여 가져올 수 있습니다.

<img width="988" alt="Screenshot 2024-08-11 at 16 44 02" src="https://github.com/user-attachments/assets/12f80881-544f-4183-a1e2-129eec819dff">

데이터를 추출하여 간단하게 txt파일로 저장해 resources폴더에 넣었습니다

<img width="1168" alt="Screenshot 2024-08-11 at 16 46 23" src="https://github.com/user-attachments/assets/99b5b471-9df7-4705-b866-74bbb1ff35be">

✨ Task
---
- [ ] 포케로그 깃허브 코드를 분석하여 필요한 데이터를 추출한다
- [ ] 데이터 저장을 인메모리 방식으로 변경한다
- [ ] 모든 GET을 동적쿼리로 변경한다

✨ Time
---
- 3일

**Comment by dwax1324** [comment]
전달이 잘 안된 것 같아서..

`동적쿼리` -> API 요청에 따른 동적인 필드를 갖는 응답 반환
`인메모리디비` -> 인메모리로 저장한다? 캐싱한다? 라는 뜻으로 사용했습니다

데이터베이스에서 사용되는 용어인 `동적쿼리`, `인메모리디비`와 완전 다르네요..
주의하겠습니다

조금 더 구체적으로 나눠서 말하면 다음과 같습니다


1. 포케로그 레포지토리를 클론하여 로컬에서 실행한다.
2. 포케로그는 `typescript`로 쓰여져있고 `vitejs` 라는 프레임워크를 사용한다.
3. 약간 조작 후 테스트 코드를 실행하면 하드코딩된 데이터를 원하는대로 출력시킬 수 있다.
4. 데이터를 추출 후 파일에 쓰기를 한다 
5. 파일을 포케로그헬퍼 resources폴더에 옮긴다.
6. API 응답에 필요한 모든 데이터는 파일 속에 있다. 어플리케이션 시작 후 데이터 파싱, 캐싱한다. 영속화 하지 않고 메모리(아마 Map,List?)로 저장하고 있는다.
7. API 요청이 들어오면 그에 맞는 응답을 한다. (도메인이나 데이터베이스는 필요가 없어진다. dto,service,controller만..)

**Comment by jongmee** [comment]
좋은 의견입니다!

1. 정적인 포켓로그 관련 데이터를 웹어플리케이션서버와 같은 클라우드 컴퓨터에 저장하는 것은 좋습니다.
 잘 변경되지 않으니 DB + 캐싱을 활용할 수도 있지만 저도 굳이? 싶네요. (지금 저장하는 데이터들에 대해서)

~2. 지금 이 `데이터 처리 방식 변경` 이슈가 어떤 문제를 해결하기 위한 이슈일까요?~
 ~- Java로 데이터 저장 자동화가 비효율적 ➡️ 쿼리를 직접 쓰면 됨 (insert 문 등)~
 ~- 새로운 데이터 도메인(바이옴 등)이 계속 생성되는데,  Entity Relationship을 고려해야 함 ➡️ NoSQL 고려~
 ~- 크기가 엄청 크지 않은 정적 데이터인데 또 다른 컴퓨터에 저장하고 커넥션이 필요함 ➡️ H2 TCP 모드 고려~
~를 고려해보셨을까요? 저도 이 글을 쓰기 위해서 좀 고민했는데 이런 고민을 해보셨나 궁금하고, 공유 받고 싶습니다! 특히 ERD 관련 부분은 관계형 DB를 써서 생긴 어려움인 것 같아요.~

더 길게 썼다가 직전 코멘트를 보고 지웠습니다 .. 정확히 무엇을 제안하는지 몰라 여러 방법대로 장단점 정리하고 있었어요 ㅎ 이슈 올릴 때는 정리해서(어떤 문제를 해결하고 싶은지, 제안한 해결 방식이 어떻게 구현되는지) 한 번에 올려주면 더 좋을 것 같아요! 저는 이슈 올라오자마자 확인하고 2시간 넘게 고민하고 있었네요 🥲 

저는 좋습니다~~

**Comment by jinchiim** [comment]
조금 고민이 되긴 합니다만, (JPA 쿼리의 편안함을 못누리고 이제는 테스트가 매우매우 중요해질 것 같기 때문, 
중복이야 `Map` 쓰면 괜찮을 것 같고?)
확실히 데이터베이스를 사용하지 않는 쪽도 고려해볼만한 부분으로 느껴지네요. 🤔

나쁘지 않은 것 같기도?  내일 더 얘기해보죠

**Comment by dwax1324** [comment]
> 저는 이슈 올라오자마자 확인하고 2시간 넘게 고민하고 있었네요 🥲

아이고 죄송합니다.. 🥲
정말 `데이터 처리 방식`에 대해 답변을 해주시고 있으셨군요 ㅎㅎ;
다음엔 조금 더 의도가 드러나도록 글을 쓰겠습니다 🙇


> 이슈 올릴 때는 정리해서(어떤 문제를 해결하고 싶은지, 제안한 해결 방식이 어떻게 구현되는지) 한 번에 올려주면 더 좋을 것 같아요!

좋은 피드백 감사합니다 
지금 다시 봐도 글이 두서가 없네요..
다음 이슈 올릴 땐 조금 더 신경쓰겠습니다!

> 저는 좋습니다~~

👍

**Comment by dwax1324** [comment]
@jinchiim 

좋습니다~ 내일 다같이 얘기해봐요☺️
